version: "3.1"

services:
  zoo1:
    image: zookeeper:3.9
    hostname: zoo1
    ports:
    - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat"
    healthcheck:
      test: ["CMD", "sh", "-c", "echo stat | nc localhost 2181 | grep -q -E 'Mode: (follower|leader)'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: always

  zoo2:
    image: zookeeper:3.9
    hostname: zoo2
    ports:
    - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat"
    healthcheck:
      test: ["CMD", "sh", "-c", "echo stat | nc localhost 2181 | grep -q -E 'Mode: (follower|leader)'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: always

  zoo3:
    image: zookeeper:3.9
    hostname: zoo3
    ports:
    - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat"
    healthcheck:
      test: ["CMD", "sh", "-c", "echo stat | nc localhost 2181 | grep -q -E 'Mode: (follower|leader)'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: always

  register:
    depends_on:
      zoo1:
        condition: service_healthy
      zoo2:
        condition: service_healthy
      zoo3:
        condition: service_healthy
    image: jam2in/zkcli:3.5.9
    environment:
      ZK_ENSEMBLE: zoo1:2181,zoo2:2181,zoo3:2181
      SERVICE_CODE: test
      CACHENODES: cache1:11211,cache2:11212,cache3:11213
      IS_REPL: ${IS_REPL}
    restart: on-failure

  cache1:
    depends_on:
      register:
        condition: service_completed_successfully
    image: jam2in/arcus-memcached${REPL_IMAGE_SUFFIX}:${IMAGE_TAG:-latest}
    command: -m 100 -p 11211 -z zoo1:2181,zoo2:2181,zoo3:2181
    hostname: cache1
    ports:
    - 11211:11211
    environment:
      ARCUS_CACHE_PUBLIC_IP: 127.0.0.1
    restart: always

  cache2:
    depends_on:
      register:
        condition: service_completed_successfully
    image: jam2in/arcus-memcached${REPL_IMAGE_SUFFIX}:${IMAGE_TAG:-latest}
    command: -m 100 -p 11212 -z zoo1:2181,zoo2:2181,zoo3:2181
    hostname: cache2
    ports:
    - 11212:11212
    environment:
      ARCUS_CACHE_PUBLIC_IP: 127.0.0.1
    restart: always

  cache3:
    depends_on:
      register:
        condition: service_completed_successfully
    image: jam2in/arcus-memcached${REPL_IMAGE_SUFFIX}:${IMAGE_TAG:-latest}
    command: -m 100 -p 11213 -z zoo1:2181,zoo2:2181,zoo3:2181
    hostname: cache3
    ports:
    - 11213:11213
    environment:
      ARCUS_CACHE_PUBLIC_IP: 127.0.0.1
    restart: always
